# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{thinking-sphinx-raspell}
  s.version = "1.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pat Allan"]
  s.date = %q{2011-08-26}
  s.description = %q{Adds spelling suggestions to Thinking Sphinx searches.}
  s.email = %q{pat@freelancing-gods.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    "LICENSE",
    "README.textile",
    "VERSION.yml",
    "lib/thinking_sphinx/raspell.rb",
    "lib/thinking_sphinx/raspell/configuration.rb"
  ]
  s.homepage = %q{http://ts.freelancing-gods.com}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{An add-on gem for spelling suggestions in Thinking Sphinx}
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/thinking_sphinx/raspell/configuration_spec.rb",
    "spec/thinking_sphinx/raspell_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<raspell>, [">= 1.2.2"])
      s.add_runtime_dependency(%q<thinking-sphinx>, [">= 1.2.12"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.1"])
      s.add_development_dependency(%q<rspec>, ["= 2.5.0"])
      s.add_development_dependency(%q<yard>, ["= 0.6.8"])
    else
      s.add_dependency(%q<raspell>, [">= 1.2.2"])
      s.add_dependency(%q<thinking-sphinx>, [">= 1.2.12"])
      s.add_dependency(%q<jeweler>, ["= 1.5.1"])
      s.add_dependency(%q<rspec>, ["= 2.5.0"])
      s.add_dependency(%q<yard>, ["= 0.6.8"])
    end
  else
    s.add_dependency(%q<raspell>, [">= 1.2.2"])
    s.add_dependency(%q<thinking-sphinx>, [">= 1.2.12"])
    s.add_dependency(%q<jeweler>, ["= 1.5.1"])
    s.add_dependency(%q<rspec>, ["= 2.5.0"])
    s.add_dependency(%q<yard>, ["= 0.6.8"])
  end
end

